FROM multiarch/qemu-user-static AS qemu
FROM arm32v7/python:2-slim-stretch
WORKDIR /tmp
COPY --from=qemu /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static
RUN pip install pyserial
COPY main.py /tmp/main.py
COPY sensor.py /tmp/sensor.py
COPY machinist.py /tmp/machinist.py
RUN rm -f /usr/bin/qemu-arm-static
ENTRYPOINT ["python", "-u"]
CMD ["/tmp/main.py"]
